version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: openjdk:11-jdk
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB

  postgresDB:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresDB
      POSTGRES_PASSWORD: compact20
