spring:
  datasource:
    #    url: jdbc:postgresql://jmcfly-db.internal:5432/jmcflydb?user=postgres&password=fnKQVGyPHKzrI3u
    url: jdbc:postgresql://localhost:5432/jmcdb?user=postgres
    username: postgres
    password: compact
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
  profiles:
    include: oauth
#server:
#  address: localhost
#  port: 8080
app:
  jwtSecret: sVlwEyVBaqwefV7zq5rqr5blYcfPQye08f7MGVA9XkHa
  jwtExpirationInMs: 30 * 60 * 1000L