spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 87143bd87a487861f2bc64d5b4e5be02
            client-secret: mvhKllvqX67V1Rpe4iN03I3MNKM5W1Ug
            redirect-uri: http://localhost:8080/kakao/login
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email
            client-name: kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


